spring.application.name=InterviewProject

server.port=8081

logging.level.org.springframework.security=DEBUG

# Set the logging level
#logging.level.root=DEBUG

# Define the log file name and path
logging.file.name=application.log
logging.file.path=D:/application.log

# Springdoc OpenAPI Configuration
#springdoc.api-docs.path=/v3/api-docs
#springdoc.swagger-ui.path=/swagger-ui.html

# MySQL database connection
spring.datasource.url=jdbc:mysql://localhost:3306/mydb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Yogesh@820
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

#Actuator health
management.endpoints.web.exposure.include=health,info 
management.endpoint.health.show-details=always





